# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ccc57ef96641560d9a554e3e9b425764a705bc1089442ed1d4ef13f30a8aeff931765bf8d9ad850c01f096caf2c8bc82dc8d3c7408480844dbe46916bff1d2f

test:
  secret_key_base: f1f0e638c34f3704e1379ba7e47c3e98b46697622308a23ac7c918ac0c9a2f7ef71b10b2babe93c5bf5d88c4c76fc7be617d52958ca3b9507c732158b30d0c51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
